### ISSUE TITLE
automatic batching interface for cloud logging client

### ISSUE THREAD

**Issue by faithseed** [GoogleCloudPlatform/google-cloud-node#1296]
The logging API support batching mode manually, where you can put multiple entry in the log.write()

`
log.write([entry, secondEntry]);
`

Is that possible to implement an batching interface to support this automatically?

for example:

```
log.add(entry);
...
log.add(another_entry);
```

In the background, logging client does periodic flush internally sending all buffered logs to cloud logging automatically. The flush is triggered when enough entries are buffered and/or at a fixed interval.

This would make the API better performance wise by making less APIs calls to cloud logging?

**Comment by stephenplusplus** [comment]
I think this is better resolved in the application layer and not our library, since every use case would likely have custom requirements around what action triggers a flush.

@filipjs do you think this is something we should try to support?

Also to consider, we use gRPC for our Logging API, which maintains an open connection to send multiple requests through. That eliminates the overhead of making several HTTP/1 calls, so it's possible the performance wins could be negligible.

**Comment by faithseed** [comment]
Thanks @stephenplusplus.

What is performance difference between

`log.write([entry, secondEntry]);`

and

```
log.write([entry]);
log.write([secondEntry]);
```

If they are considered equally efficient, maybe we should document that in the developer doc and encourage users to choose either one of them.

**Comment by stephenplusplus** [comment]
We haven't measured the performance difference, and I think it might be micro-optimization if we did or recommended an approach one way or the other. I think it's best left to the application and its concerns to make the best decision for their use.

**Comment by filipjs** [comment]
Our documentation recommends batching as it's more efficient and doesn't consume QPS quota that quickly (https://cloud.google.com/logging/quota-policy)
I'm not sure how gRPC is counted for QPS purposes.

**Comment by stephenplusplus** [comment]
@jgeewax any insight into how QPS are measured when using gRPC?

**Comment by jgeewax** [comment]
@rimey : Any idea? Basically is "1 write log entry" equivalent to a single gRPC call? or is it the number of log entries written in the gRPC call?

Or in more specific terms, is `log.write([entry1, entry2])` counted as 1 log write entry? or 2?

**Comment by stephenplusplus** [comment]
Friendly ping @rimey -- or anyone else who can help.

cc @ofrobots

**Comment by ofrobots** [comment]
This thread conflates performance implications of batching with quota implications.

> Or in more specific terms, is log.write([entry1, entry2]) counted as 1 log write entry? or 2?

I think the more interesting question is this:

```
log.write(foo);
log.write(bar);
```

Are those counted as two `entries.write` calls? If so, as I expect, we need buffering.

**Comment by zbjornson** [comment]
I'm 99% sure the protocol doesn't matter; it's the actual command that counts. (bunyan-stackdriver is built on google-cloud/logging and thus uses gRPC, and I know I hit the quota, although that was ages ago.)

From the [docs](https://cloud.google.com/logging/docs/api/reference/rest/v2/entries/write):

> To improve throughput and to avoid exceeding the quota limit for calls to entries.write, you should write multiple log entries at once rather than calling this method for each individual log entry.

The approach in bunyan-stackdriver is to flush the buffer every 500 ms (default; configurable). I have yet to find a maximum total payload size, only a per-Entry size (112640 bytes), so there's no forced flush if the buffer gets to be a certain size (although that would be good for controlling memory usage). [cloud-trace-nodejs](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/v0.6.x/src/trace-writer.js#L200) does both time batching and buffer size control.

**Comment by munangst** [comment]
The maximum total payload size for entries.write is 5 MB. We've added it to our docs here: https://cloud.google.com/logging/quota-policy

**Comment by ofrobots** [comment]
@munangst The debate at this point is whether two calls to `entries.write` over the same gRPC connection would count as two calls as per the quota policy. I suspect that's the case, but the comment here https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1296#issuecomment-217894072 is causing confusion.

**Comment by munangst** [comment]
As far as I know each `entries.write` call counts as one request for quota purposes, regardless of whether it's made over gRPC or JSON, and regardless of how many entries are batched into it.

**Comment by ofrobots** [comment]
@munangst thanks a lot for chiming in!

@stephenplusplus Given the above response can we upgrade this issue from the `question` label to `enhancement`?

**Comment by stephenplusplus** [comment]
@ofrobots @zbjornson how do you think this should look from an API standpoint, and behave internally?

**Comment by ofrobots** [comment]
Here are my thoughts on this so far:

It would good to have two configuration options: 
* `bufferSize`: The [quota policy](https://cloud.google.com/logging/quota-policy) requires individual calls to `entries.write` to be less than 5MB. This would be a number of bytes to buffer clamped at 5MB. A value of 0 would imply that no buffering should be done.
* `flushDelay`: The buffer, regardless of size, should be flushed every `flushDelay` milliseconds. The global quota for a project is 500 calls per second, so 250 - 500 ms would be a good default for this (that allows 125 - 250 services to exist per project). A value of 0 should imply that no time based flushing should be done (i.e. `bufferSize` applies).

From the API perspective there might be a few options:

1. If buffering applies, `Log.prototype.write` queues the entries into a buffer along with the callback to be called when the buffer drains. This is not semver major, but will cause a latency spike when tonnes of queued callbacks get called after the drains. It is not clear if users are really waiting on the callbacks anyway – certainly the `logging-bunyan` users won't be  – so it would be good if we can avoid the latency spike somehow.
1. If buffering applies, `Log.prototype.write` queues the entries into a buffer – the callback would be called to indicate 'successfully queued' (i.e. it will never error). We also make `Log` an EventEmitter emitting `drain` and `error` events to allow users to track status. This is a semver major change.
1. Add a new method `Log.prototype.getWriteStream` which returns a `WritableStream` interface. The stream emits `drain` and `error` events as appropriate to allow users to monitor status.

Thoughts?

@stephenplusplus do you think you will have time for this in the near future?

/cc @matthewloring

**Comment by zbjornson** [comment]
Agreed with the two bullet points @ofrobots listed. Only addition is that a single entry has to be no more than 112640 bytes; 5MB is the limit for the whole batch. I'm not sure what the behavior should be for an oversized entry since you can't just truncate it -- options could be discarding it silently, discarding it with a warning, discarding it with an error, trimming random properties or trimming largest properties. In case it helps, here's how batching is done in a few other transports: [bunyan-stackdriver](https://github.com/mlazarov/bunyan-stackdriver/blob/master/lib/bunyan-stackdriver.js#L112), [bunyan-cloudwatch](https://github.com/mirkokiefer/bunyan-cloudwatch/blob/master/index.js#L27), [cloud-trace](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/v0.6.x/src/trace-writer.js#L200).

I'm not sure what the use case is for having a callback to indicate that a single log entry has been written. Maybe if someone wants to ensure a mission-critical entry is written (compared to most entries which are often "try your best to log")? In any case, node's `writable.write` allows an optional callback for when that chunk is flushed, so it is idiomatic.

I'm partial to exposing a real stream interface so that this follows node.js idioms without caveat -- you'd have the `drain` event to listen on when the queue is empty, for example. Is there a need for the separate `Log.prototype.getWriteStream` method, instead of just making `LoggingBunyan` inherit from `stream.Writable` (as discussed in #1988)? In addition, that seems like it would provide the easiest way to listen to any sort of error (GCP API errors, serialization errors, etc.) -- in a single listener.

**Comment by ofrobots** [comment]
After some discussion with @jmuk I discovered today that batching or 'bundling' for requests is a feature that [google-gax](https://www.npmjs.com/package/google-gax) already supports. In fact the gax library for logging should already support 'bundling' as per [this configuration](https://github.com/googleapis/googleapis/blob/b2370781bc3c449a71295b9c72a01f77b8085402/google/logging/v2/logging_gapic.yaml#L356).

This means that big bulk of the buffering features that are being requested here would be subsumed by the work in https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1859.

@stephenplusplus is there an ETA on when the `logging` migration to `gax` is expected to happen?

**Comment by stephenplusplus** [comment]
Logging is now converted to GAX-- is there anything that we need to do to enable the features requested in this issue?

**Comment by ofrobots** [comment]
IMO the features requested in this issue are addressed by bundling features of GAX.

From the API perspective the integration with GAX at the moment goes with option 1. Down the road it might be good to consider adding a WritableStream interface to `Log` as well – but that is an independent feature request.

**Comment by stephenplusplus** [comment]
Awesome, thanks for the info!
