### ISSUE TITLE
Question : Is the installed package really 795.3 MB ?

### ISSUE THREAD

**Issue by avnercompit** [GoogleCloudPlatform/google-cloud-node#1535]
I installed 0.38.3.
The folder in the node_modules directory is 795.3 MB.

For micro-services this is really uncomfortable it increases a lot of install and transfer times and requires bigger storage spaces for my machines. 

And the only thing I'm using is BigQuery.

Did I get something wrong ? Is there a way to install just BigQuery ?

**Comment by stephenplusplus** [comment]
This just came up on Twitter: https://twitter.com/mluggy/status/770221258533380096

Old versions of npm don't run `dedupe` for you. This is a command which finds compatible ranges of dependencies between your dependencies, and removes them from disk. Since npm version 3, `dedupe` is run *before* downloading any dependencies, so no extra disk space or download time is wasted.

For example, on npm 3, `npm install google-cloud` results in a ~45MB download. With npm 2, you get the larger download size (~700MB from my testing). If you run `npm dedupe`, you should end up around the npm 3 size.

So the two options for best results are;

1) Upgrade `npm` to version 3.x
2) If that's not possible, run `npm dedupe` after installing

**Comment by stephenplusplus** [comment]
I've added a note in our Troubleshooting docs explaining this: #1536
