### ISSUE TITLE
Need to ensure we use lower-case gRPC header keys

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-node#1545]
**This might be a no-op, but please double check. Filing this issue just in case.**

We need to ensure that all headers used for gRPC are written in lower-case. Please review this [Pull Request](https://github.com/GoogleCloudPlatform/gcloud-python/pull/2212) for reference of what needs to be updated.

Again, perhaps this doesn't apply to your language. Feel free to comment and then close the issue (after double checking).

**Comment by stephenplusplus** [comment]
This is actually quite well timed, since we just got an issue about setting headers for Datastore: #1542. That issue already specifies the headers as lowercase, so I'll just be copying from that example.

As our library stands currently, we don't set any headers at all. That's handled in gRPC for us, we just give it an auth client from [`google-auth-library`](https://github.com/google/google-auth-library-nodejs) and it figures out the rest.
