### ISSUE TITLE
Bucket writeStream bytesWritten is undefined

### ISSUE THREAD

**Issue by chrisabrams** [GoogleCloudPlatform/google-cloud-node#1686]
#### Environment details

  - OS: OS X 10.11.6
  - Node.js version: 6.7.0
  - npm version: 3.10.3
  - google-cloud-node version: 0.41.2

#### Steps to reproduce

```
const bucketId = 'YOUR_BUCKET_ID'
const fs = require('fs')
const gcloud = require('google-cloud')
const path = require('path')
const storage = gcloud.storage({
  projectId: 'YOUR_PROJECT_ID',
  keyFilename: './credentials.json'
})

const fooPath = path.join(__dirname, './foo.txt') // contents of foo are "Hello World!"

// FS example
var readStream = fs.createReadStream(fooPath)
var writeStream = fs.createWriteStream(path.join(__dirname, './foo2.txt'))
readStream.pipe(writeStream)

writeStream.once('finish', function() {
  console.log('FS Bytes', writeStream.bytesWritten)
})


// Gcloud Example
const bucket = storage.bucket(bucketId)
var localReadStream = fs.createReadStream(fooPath)
var remoteWriteStream = bucket.file('foo.txt').createWriteStream()
localReadStream.pipe(remoteWriteStream)

remoteWriteStream.once('finish', function() {
  console.log('GC Bytes', remoteWriteStream.bytesWritten)
})
```

You will see the `fs` version of the test `console.log` the number of `bytesWritten` where the `gcloud` version of the test will `console.log` `undefined`.

**Comment by stephenplusplus** [comment]
As far as I know, there isn't a spec of properties that all writable streams must expose. Have you seen other streams expose this data?

**Comment by chrisabrams** [comment]
Outside of what `fs` exposes? I am able to get the `bytesWritten` when I stream anything from Express or Multer, Express's core file upload receiver.

**Comment by chrisabrams** [comment]
`bytesWritten` is in the Node.js docs for the writeStream: https://nodejs.org/api/fs.html#fs_writestream_byteswritten

**Comment by stephenplusplus** [comment]
I believe you can count the bytes with something like:

```js
var through = require('through2')
var countStream = through(function(chunk, enc, next) {
  this.bytesWritten += Buffer.byteLength(chunk)
  this.push(chunk, enc)
  next()
})

var byteCountStream = countStream()
localReadStream.pipe(byteCountStream).pipe(remoteWriteStream)

remoteWriteStream.once('finish', function() {
  console.log('GC Bytes', byteCountStream.bytesWritten)
})
```

Found a modular that looks like it does something similar: https://github.com/brycebaril/node-stream-meter. You can also subclass a `PassThrough` stream if you don't want the weight of another dependency.

RE: bytesWritten in the Node docs, that's only describing a FileSystem write stream:

```js
var ws = new stream.Writable()
ws.bytesWritten
> undefined

var fws = fs.createWriteStream('/tmp/test')
fws.bytesWritten
> 0
```

I'm not sure implementing here would be a good idea, since we are making a remote request. For example, if you tried to read the `bytesWritten` at a certain point in the operation, it might not reflect what the upstream has processed yet. And then an error in the pipeline could tarnish that number.

Let me know if any of the proposed solutions don't work, and we will keep at it 👍

**Comment by chrisabrams** [comment]
@stephenplusplus yes I saw a similar solution in your resumable repo ;) I'll try the two examples you mention.
