### ISSUE TITLE
Support generic Batch HTTP requests

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-node#1765]
We got feedback on this page that we don't have any code samples. https://cloud.google.com/bigquery/batch

The API clients support batch requests, https://developers.google.com/api-client-library/java/google-api-java-client/batch but I don't think the Cloud libraries do.

**Comment by bjwatson** [comment]
@stephenplusplus @callmehiphop @jmdobry I checked with @tswast, and we can wait on this until post-beta.

**Comment by tswast** [comment]
Closing this since batch is considered a legacy feature. It is not supported in new gRPC-native APIs.

**Comment by c0b** [comment]
but is there equivalent thing in gRPC-native APIs? @tswast @stephenplusplus

the use case is to delete multiple storage objects, we used to use S3 storage that has multiple objects delete api,
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#deleteObjects-property

wonder if GCS has something similar? I'm not seeing any, but the gcloud batch API could be a close one, it's even better because it can delete multiple different cloud objects like delete gcs objects and bigquery table in a single batch call?
https://cloud.google.com/storage/docs/json_api/v1/objects/delete

**Comment by tswast** [comment]
Storage uses the batch APIs I describe here, not gRPC. I closed the issue since it should not be implemented in general, since it doesn't apply to all APIs. Makes sense to implement for Storage if the client library doesn't already support it.

**Comment by c0b** [comment]
what I see is the batch API is pretty well supported across multiple GCloud product; I use Storage as just one example of good use for mutli objects delete; but potentially other Cloud objects also need multi delete, for bigquery situations like user want to delete multiple GCS objects and delete multiple bigquery tables, as well as another POST for a new query...

Would it make sense to support a generic Batch HTTP requests across multiple Cloud product? for where batch API applies

1. https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch
2. https://cloud.google.com/bigquery/batch
