### ISSUE TITLE
Not clear if I should import "@google-cloud/pubsub" or "google-cloud" 

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/google-cloud-node#1890]
https://cloud.google.com/pubsub/docs/reference/libraries#client-libraries-install-nodejs
says I should run `npm install --save @google-cloud/pubsub` 

but https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.45.0/pubsub
says `npm install --save google-cloud`

Which one should I use? Are they the same library? Can you align on only one?

**Comment by stephenplusplus** [comment]
Yep, same module. Because there are so many services we support, we decided to break them into modules. So, if you just need Pub/Sub, without the others (see our README for the full list, but BigQuery, Bigtable, Datastore, Storage, Vision, etc), then just install it directly (`@google-cloud/pubsub`). If you need a few, then go for the bundled module, `google-cloud`, and access it through there. Examples of those install and require commands can be found [here](https://github.com/GoogleCloudPlatform/google-cloud-node#google-cloud-pubsub-alpha).

**Comment by steren** [comment]
Would it make sense to update https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.45.0/pubsub to use the `npm install --save @google-cloud/pubsub`?

As a user, these 2 modules confused me and made me wonder if they were different.

**Comment by stephenplusplus** [comment]
The docs from that link are referring to the bundled module, which is the default way of viewing our docs. There's a drop down at the top which shows what module is actively being viewed. When you flip over there, say you select `google-cloud/pubsub`, you are redirected to https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.7.0/pubsub, which changes the context with the install command.

I think we can keep this behavior, but leave a banner message of some sort at the top of each, making sure users know we have two entry points to the API.

Issue re-opened!

**Comment by bjwatson** [comment]
@omaray We need some PM guidance on this.

**Comment by lukesneeringer** [comment]
This has been decided: the meta-package is now officially deprecated.
