### ISSUE TITLE
Speech SDK returns Client GRPC deadline too short

### ISSUE THREAD

**Issue by blerest** [GoogleCloudPlatform/google-cloud-node#1894]
Hi,

Sometime the speech nodejs SDK returns the following error:

> Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 59.99929095065454 second(s). Required at least: 61 second(s).

And the audio stream is destroyed after that:

> stream was destroyed","stack":"Error: stream was destroyed\n    at /root/sip.rogervoice.com/speech_recognition/node_modules/pump/index.js:45:21\n    at call (/root/sip.rogervoice.com/speech_recognition/node_modules/pump/index.js:50:3)\n    at Array.forEach (native)\n    at /root/sip.rogervoice.com/speech_recognition/node_modules/pump/index.js:72:16\n    at f (/root/sip.rogervoice.com/speech_recognition/node_modules/once/once.js:17:25)\n    at /root/sip.rogervoice.com/speech_recognition/node_modules/pump/index.js:31:5\n    at f (/root/sip.rogervoice.com/speech_recognition/node_modules/once/once.js:17:25)\n    at DestroyableTransform.onfinish (/root/sip.rogervoice.com/speech_recognition/node_modules/pump/node_modules/end-of-stream/index.js:30:18)\n    at emitNone (events.js:91:20)\n    at DestroyableTransform.emit (events.js:185:7)","level":"error","timestamp":"2016-12-21T11:07:37.170Z

There is no information about this duration on your documentation. I don't know how to change it.

Here how I use the SDK:

```
createRecognizeStream({
            config: {
                encoding: 'LINEAR16',
                sampleRate: 16000,
		languageCode: 'en-US',
                maxAlternatives: 1,
	        profanityFilter: true
            },
            singleUtterance: true,
            interimResults: true,
            verbose: true
})
```

The audio stream is a continuous realtime stream.

**Comment by stephenplusplus** [comment]
Thank you for reporting.

@jmuk any ideas?

**Comment by bloodcarter** [comment]
@stephenplusplus @blerest Same problem!

**Comment by jmuk** [comment]
Hmmm, it seems you are using the streaming method, I'm not sure what's the right way to specify the timeout.

- The autogen layer allows the timeout through the call options, while the hand-written layer seems not providing the code path. I'll fix the hand-written layer to allow customizing the timeout.
- I will investigate how the timeout works for streaming method.

**Comment by bloodcarter** [comment]
@jmuk Yes, I can confirm that recognizeStream drops with  the error message randomly, but at least 1 time per minute. I found the workaround by catching 'error' event and recreating the stream, but.....Would love to this to be fixed. Please, keep us posted.

**Comment by blerest** [comment]
@stephenplusplus @jmuk do you have any news regarding this issue? This issue cause a lot of problems on our production.

**Comment by swcloud** [comment]
There is API limit for the audio length, which is 1 minute for the streaming API call (StreamingRecognize).

https://cloud.google.com/speech/limits#content

**Comment by blerest** [comment]
@swcloud You are true. This error is throwing when 1 minute of audio is exceeded. Maybe it is a good idea to change the error message to a more appropriate message?

Second question: do you plan to remove this limite of 1 minute? It is a problem for us as our client can speak more than 1 minute.

**Comment by jmuk** [comment]
(my responses are delayed since I'm on vacation. Sorry!)

Okay, I've noticed that the `streamingRecognize` will accept up to 60 seconds according to https://cloud.google.com/speech/limits#content

Let's do the following things:
- increase the default timeout (currently 60 seconds, but probably at least 60 * 3 + 5 = 185 seconds)
- allow specifying the timeout at the API level

**Comment by swcloud** [comment]
@blerest If your audio length is more than 1 minute, you should make asynchronous request, which has 80-minute limit.

**Comment by damienjars** [comment]
Hello, I'm trying to use the 'listen' mode and after 20 seconds, the stream is destroyed even if the 'isFinal' flag is true or false. Do you have any idea why ?

Thx

**Comment by ovikholt** [comment]
Guys, you should have a look at how this @jerjou is trying to solve this, here: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/517

**Comment by jerjou** [comment]
Oh wow deja vu - it's like, the same conversations we're having over in python land are being had here in nodejs land too :-)

@damienjars the 20-second limit is probably because of the timeout that jmuk [mentioned above](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1894#issuecomment-270994752) - you'll want to set the timeout to `60 * 3 + 5 = 185` seconds to get the full [60 seconds](https://cloud.google.com/speech/limits#content).

Otherwise, the easiest workaround I could think of was to make requests with `single_utterance=True`, and simply reopen the stream after every utterance (while keeping a small ring buffer of audio so you don't miss any speech between the streams).

This works as long as there isn't more than 60 seconds between utterances. If you anticipate a lot of silences in your audio, I'd imagine you'll need to do some [speech detection](http://dsp.stackexchange.com/questions/1522/simplest-way-of-detecting-where-audio-envelopes-start-and-stop) (or something more manual) before opening up the stream in the first place (again, with the small ring buffer). If you anticipate your speakers to drone on for more than 60 seconds without a break... then maybe you have bigger problems :wink:

**Comment by jmuk** [comment]
My PR #1915 increases the timeout to 190 seconds which should be sufficient to recognize 60 seconds audio. I'm also adding more comments for the audio duration limits, and allow customizing timeout (the problem on google-cloud-node specific is, the current interface doesn't allow timeout customization).
