### ISSUE TITLE
Cloud NL score and magnitude values have way more decimal points than they should?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1896]
If you use language.detectSentiment, it seems like the numbers that come back are super duper long, but the NL team says they round them to a single decimal point.

Can we confirm that we're not doing some jumbled parsing here? I'm guessing that this is an issue with floats and may lie upstream in Node's gRPC implementation...

**Comment by dhermes** [comment]
Binary can only represent half integers exactly.

**Comment by jgeewax** [comment]
Yep:

```js
> 0.1 + 0.2
0.30000000000000004
> parseFloat('0.3')
0.3
> JSON.parse('{"score": 0.3}')
{ score: 0.3 }
> JSON.parse('{"score": 0.3}').score - 0.1
0.19999999999999998
```

It seems like just blindly parsing the results from the API (ie, `0.3`) shouldn't show up as float-related issues, though I'm not 100% certain on that.

**Comment by stephenplusplus** [comment]
This is how the gax API returns it to us:

```js
{
  documentSentiment: {
    magnitude: 0.20000000298023224,
    score: 0.20000000298023224
  },
  language: 'en',
  ...
}
```

// cc @jmuk @murgatroid99

**Comment by jgeewax** [comment]
So could be in gRPC world. No biggie then. Let's kill this.

**Comment by dhermes** [comment]
@jgeewax Doing something like `0.3 - 0.1` shouldn't be your concern. Though it does produce one bit of difference. The "standard" rep is:

```python
>>> (0.3 - 0.1).hex()
'0x1.9999999999999p-3'
>>> (0.2).hex()
'0x1.999999999999ap-3'
```

So in Javascript, if you manually scale by `2^(-exponent)` and convert to hex, you get the same thing:

```javascript
> (8 * (0.3 - 0.1)).toString(16)
'1.9999999999999'
> (8 * (0.2)).toString(16)
'1.999999999999a'
```

The problematic value is from a `float` (i.e. "single precision", i.e. 32-bit precision) rather than a `double`:

```javascript
> (8 * (0.20000000298023224)).toString(16)
'1.99999a'
```

The 6 hex digits `99999a` don't actually represent 24 bits of a mantissa, but 23, since `a = 1010` in binary.
