### ISSUE TITLE
Please implement get_serving_url() in ptyhon api to node 

### ISSUE THREAD

**Issue by kriptontr** [GoogleCloudPlatform/google-cloud-node#1920]
Let us take advantage of magic image urls in node api referenced as there 
https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.images#Image_get_serving_url

**Comment by stephenplusplus** [comment]
Can you elaborate how you see this being used here?

**Comment by stephenplusplus** [comment]
I don't see much we can do with this without further clarification, but for new features, please suggest over here so they can be voted on: #1338. Thanks!

**Comment by bodinsamuel** [comment]
Hi,
It's been a long time since this issue but I feel the need to +1 
get_serving_url was implemented in python, java and php client (as far as I can tell).

It will be used (mostly I think) to generate a resized images, with the parameters size/crop. Its very useful and also free of charge, which is a must have. Currently nodejs developper need to implement their own system, either on the fly with cloud function or upload a resized crop everytime they need it)

Ref:
https://cloud.google.com/appengine/docs/standard/python/refdocs/google.appengine.api.images#google.appengine.api.images.get_serving_url

Thanks
