### ISSUE TITLE
[autogen] add auto-generated unit tests

### ISSUE THREAD

**Issue by jmuk** [GoogleCloudPlatform/google-cloud-node#1930]
@shinfan has been working for the auto-generation of unit tests (for the autogen layers), the results are seen under https://github.com/googleapis/api-client-staging/tree/master/generated/nodejs/google-cloud-node/packages right now.

It would be beneficial to merge them into the GCN repository.

**Comment by stephenplusplus** [comment]
I believe we discussed this before, and thought `api-client-staging` was the winner for hosting these tests. I don't feel too strongly about this if there aren't better options, but would prefer the repo that generates the files should test those files they generate. Since that development doesn't happen here, it feels out of place.

**Comment by stephenplusplus** [comment]
@jmuk are there APIs left that need to have tests auto-generated?

**Comment by jmuk** [comment]
I've been detached from the progress here. reassigning to @swcloud ?

**Comment by stephenplusplus** [comment]
These are coming in as we're bringing in the partial APIs and full-GAPIcs. I'm not sure this issue is necessary, but to any interested parties, please re-open if that's an incorrect assumption.
