### ISSUE TITLE
logging-bunyan should be a proper Writable stream

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#1988]
Originally raised here: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1977#issuecomment-278743604

> This implementation doesn't provide a true stream.Writable, which means Bunyan's reemitErrorEvents won't work.

**Comment by stephenplusplus** [comment]
Should I assign you? :)

**Comment by ofrobots** [comment]
Yes, please!

**Comment by danoscarmike** [comment]
@ofrobots please confirm if this changes surface?  Thanks.

**Comment by ofrobots** [comment]
This wouldn't affect the API of `logging` module. It would be a semver major change for the `logging-bunyan` module which is currently marked 'experimental'.

**Comment by ofrobots** [comment]
@zbjornson I wanted to make sure I fully understand your motivation for requesting this feature. You stated that you wanted `reemitErrorEvents` to work. Is that all, or can you think of another motivation for why the stream must be a real `Writable`?

I am guessing the real feature you are asking for is for us to provide a way to report error events (hopefully via `reemitErrorEvents`). Making the stream a `Writable` seems to be an implementation detail. Correct?

**Comment by zbjornson** [comment]
Yeah, emitting error events is probably the only one that is noticeable to most users (and me). Node's `Writable` base class provides buffering (as well as some prototype methods). I don't know what the impact of not buffering would be since after #1296 is resolved you'll probably be buffering within gcloud-node.

(On the other hand, if you implement `_writev` then you might not need to buffer in gcloud-node...)

(FWIW, #1296 is way more important to me than this one -- 1296 is a blocker to adoption.)
