### ISSUE TITLE
google-cloud/speech connection status (gRPC?)

### ISSUE THREAD

**Issue by lpercifield** [GoogleCloudPlatform/google-cloud-node#1993]
Hello all,
I'm currently using an implementation of the speech module and am having connection dropout issues (hardware issue), but am not receiving any status/error messages about connection availability or socket dropouts. I'm interesting in seeing if there is any way to have connection status messages/errors bubble up to the application level.

The easiest way for me to replicate this issue is to disconnect from a network and start the speech module. Seems to fail silently...

Here is the implementation and a ticket I opened in the library repo: https://github.com/evancohen/sonus/issues/34

Thanks and keep up the good work!

**Comment by shinfan** [comment]
@jmuk  Seems related to our timeout exception handling. Do you mind taking a look into this?

**Comment by stephenplusplus** [comment]
@lpercifield would you mind seeing if this is still an issue? `@google-cloud/speech` version 0.10.2 is out, which uses a much thinner surface underneath (docs: https://googlecloudplatform.github.io/google-cloud-node/#/docs/speech/0.10.2/speech)

Thank you for your patience.

**Comment by eoogbe** [comment]
Hi @lpercifield,
Thank you for reporting this.

Since the time that you reported this issue, we released an entirely new version of google-cloud-speech with significant alterations. Could you upgrade to the newest version (note that code changes will be necessary to use the new thing; your existing code will use the former, now deprecated code path), and it should fix this problem for you.

I am going to close this, but feel free to re-open if the issue persists.

**Comment by eoogbe** [comment]
I am no longer on the team
