### ISSUE TITLE
language: allow raw request objects to `annotate()`

### ISSUE THREAD

**Issue by jmuk** [GoogleCloudPlatform/google-cloud-node#1998]
From internal feedback from the API team:

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/language/src/document.js#L235

`annotate` has options for features, named as `entities`, `sentiment`, and `syntax`. They are different from the terms in the API reference, thus, we should put the references in the comments of each features (`entities` -> `extractEntities`, `syntax` -> `extractSyntax`, `sentiment` -> `extractDocumentSentiment`). Also better to have a link to https://cloud.google.com/natural-language/docs/reference/rest/v1/documents/annotateText#features

cc: @monattar

**Comment by stephenplusplus** [comment]
I think `annotate` was meant to accept a raw API request object in the form of https://cloud.google.com/natural-language/docs/reference/rest/v1/documents/annotateText#features, but it didn't end up that way. So instead of explaining the mapping of `entities` to `extractEntities`, we should allow this request to "just work":

```js
vision.annotate({
  extractEntities: true,
  extractSyntax: true
}, function() {})
```

So if they're using the upstream API docs as a reference, they won't need to use our aliases.

**Comment by jmuk** [comment]
that should work. Thanks!

**Comment by jmuk** [comment]
Well, sorry for my misunderstanding, but I think the point of this feedback is the documentation and therefore simply allowing the those fields additionally isn't the solution (that would be a good thing to do though). The comments for those features fields should be updated in addition.

**Comment by stephenplusplus** [comment]
I think what we want is:

- Option aliases stay the same
- Add "(Alias for  `options.fullNameVariant`)" (reference: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/764f010d1c557f3be30aaf7e64246937a7ea352d/packages/compute/src/region.js#L257)
- Update [this link](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/51e49670c9dbb6889de0fcc1e729c7b1d84b6b7d/packages/language/src/document.js#L234) to https://cloud.google.com/natural-language/docs/reference/rest/v1/documents/annotateText#features

Since we're in there, and since it's a pattern in other areas of the API, it would also be nice to allow the full name variants to work as well.

**Comment by jmuk** [comment]
Current options vocabulary is good and we can keep it -- what API team cares is the relationship with the API documentations. Thus probably only the updating the link could be sufficient? @monattar for the confirmation.
