### ISSUE TITLE
namespace & kind error check

### ISSUE THREAD

**Issue by diiiego83** [GoogleCloudPlatform/google-cloud-node#2067]
Hi,
is there any way to add an error check based on namespace and/or kind for a query operation in datastore?
Right now If i specify  a wrong namespace and/or kind the query ends with an null error.
It will be a great feature.

Thanks :),
Diego

**Comment by stephenplusplus** [comment]
What do you mean by "wrong" exactly? Can you show an example of what's happening now and what you'd like to see?

**Comment by diiiego83** [comment]
Hi Stephen,
for example test_namespace and test_kind exist:

`var query = gcd.createQuery(test_namespace, test_kind+'xxx');`
`query.run((err, entities, info) => {`
`      console.log(err); // err is null (test_kind+'xxx' does not exist i would like to have an error here)`
`});`

Thanks,
Diego

**Comment by stephenplusplus** [comment]
Thank you for the example. We won't be able to do anything in this library, because we don't know from the response whether it exists or the query simply didn't return any matches.

I'll ping @pcostell from the Datastore team, in case he thinks this is an error as opposed to a query without results. Feel free to discuss in this thread, and if there is reason for us to make any changes in the library, we certainly will.
