### ISSUE TITLE
Vision 'detect' method doesn't return values when image is remote url

### ISSUE THREAD

**Issue by talkaboutdesign** [GoogleCloudPlatform/google-cloud-node#2087]
When passing in local image url API works great. When passing remote image url api does not provide any results. Here is my code for reference: 

```
'use strict'

// Imports the Google Cloud client library
const Vision = require('@google-cloud/vision');

// Your Google Cloud Platform project ID
const projectId = 'my-id-is-here';

// Instantiates a client
const visionClient = Vision({
  projectId: projectId,
  keyFilename: 'service.json'
});

var img = 'https://d13yacurqjgara.cloudfront.net/users/995236/screenshots/3024565/day-36-normal.png';
var types = ['label','properties'];

visionClient.detect(img, types, function(err, detection, apiResponse) {
    // console.log(detection['labels']);
    // console.log(detection['properties']['colors']);

    if (err) throw err
    console.log(JSON.stringify(apiResponse, null, 2))
});
```

**Comment by talkaboutdesign** [comment]
Here is the error I get. 

```
PartialFailureError: A failure occurred during this request.
    at /Users/max/Library/Mobile Documents/com~apple~CloudDocs/Design Hunt/Image Analysis/node_modules/@google-cloud/vision/src/index.js:420:15
    at /Users/max/Library/Mobile Documents/com~apple~CloudDocs/Design Hunt/Image Analysis/node_modules/@google-cloud/vision/src/index.js:121:5
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

FYI this is running on local machine.

**Comment by stephenplusplus** [comment]
The API is returning an error for that image:

```js
{
  code: 500,
  message: 'image-annotator::error(12): We can not access the URL currently. Please download the image and pass it in.'
}
```

To access this error:

```js
console.log(err.errors[0].errors)
```

I know that's pretty goofy, but the layering of `err` is:

- **err**: PartialFailureError - Since the API accepts multiple images and multiple annotation types, some can fail, while others can succeed. We return these in a single argument, the error to the callback
  - **errors** - This array holds the errors
    - **errors[0]** - This is the first error of the partial failure
      - **image** - This lets you know what image the error is referencing
      - **errors** - There can be multiple reasons why the error occurred (perhaps it was a straight-up 500 like in this case, or an image was unfit for the requested annotation type)
        - **errors[0]** - The actual error from the API
          - **code** - The HTTP response status code
          - **message** - The HTTP response status message
          - **type** - The detection type that was requested (e.g. `labels`)

Sorry for the confusion.

As far as why Vision cannot access the URL, I'm not sure-- could you open the question on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+google-cloud-vision? Googlers from the various service APIs look through those questions and are usually pretty quick to respond.

**Comment by talkaboutdesign** [comment]
Thank you. That helps.

**Comment by talkaboutdesign** [comment]
Is it possible to send base64 encoded image through the detect api in node instead of file name?

**Comment by stephenplusplus** [comment]
Yep, if provided as a buffer, either like:

```js
var image = new Buffer('...', 'base64')
```

Here's an example with `request`:

```js
request('image-url', { encoding: null /* returns a Buffer */ }, function(err, resp, body) {
  vision.detect(body, ['label','properties'], function(err, detection, apiResponse) {})
})
```

**Comment by Jasonspd** [comment]
I was detecting remote URL images with an older version of google cloud and it worked fine. However since google cloud 0.50.0, google-cloud has been deprecated.
`npm WARN deprecated google-cloud@0.45.2: The google-cloud meta-package is not recommended; install individual packages.`

I now get the same error as you with remote URL images when using the new way to access vision: `@google-cloud/vision`

**Comment by sthielen** [comment]
I've been having the same issue starting yesterday (7/14), specifically with passing the URL of an image being served from AWS Cloudfront (something like: `https://screenshots.cdn.gometa.io/A5A74799-8D42-44E4-8D5D-D54BA1B92CD9.jpg`). The problem is intermittent & I cannot consistently reproduce. Sometimes it works for an hour, then goes back to failing with that `500` error.

Temporarily solved on our end by fetching the image and passing the buffer instead of the remote URL, but wanted to comment letting you folks know. It could easily be an issue with regard to the CDN, but I don't have enough exposure into the error to understand why the fetch is failing.
