### ISSUE TITLE
Document callback.nextQuery in query()

### ISSUE THREAD

**Issue by jcondit** [GoogleCloudPlatform/google-cloud-node#2174]
Can you document the callback.nextQuery parameter for the BigQuery query() function?

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/bigquery/src/index.js#L714

Without documenting this parameter, the generated docs are misleading. See https://issuetracker.google.com/36408121.

**Comment by stephenplusplus** [comment]
By default, `nextQuery` is not included in the response, which is why we don't include it in the documentation, instead using the example to demonstrate how it is meant to be used. That example for BigQuery is:

> To control how many API requests are made and page through the results manually, set `autoPaginate` to `false`.
```js
var callback = function(err, rows, nextQuery, apiResponse) {
  if (nextQuery) {
    bigquery.query(nextQuery, callback);
  }
};

bigquery.query({
  query: query,
  autoPaginate: false
}, callback);
```

The key part here is `autoPaginate: false`-- that's the argument which is `true` by default, and when disable, will change the signature of the callback.

Since it is not the default set of arguments to the function, I think we'd end up confusing more users by stating that their callback will receive the `nextQuery` argument.

However, I do think we messed up-- we shouldn't show that the callback receives `apiResponse`, because that doesn't come by default either.

@callmehiphop does all that sound correct?

**Comment by smarigowda** [comment]
Thank you for the detail response. I am now able to get the apiResponse.
