### ISSUE TITLE
Error: Audio data is being streamed too fast. [node]

### ISSUE THREAD

**Issue by FrancescoDiMaggio** [GoogleCloudPlatform/google-cloud-node#2191]
## Introduction
I'm trying to obtain the transcription from a 34MB file located in the 'audios' directory using this code:

```javascript
const Speech = require('@google-cloud/speech');
const fs = require('fs');

const projectId = '<project_id>';

const speechClient = Speech({
  projectId: projectId
});

const fileName = 'audios/7868_20160913_2000_ARD.flac';

const request = {
  config:{
    encoding: 'FLAC',
    sampleRate: 48000,
    languageCode: 'de-DE'
  }
};

fs.createReadStream(fileName)
  .on('error', console.error)
  .pipe(speechClient.createRecognizeStream(request))
  .on('error', console.error)
  .on('data', function(data) {
    if(data.endpointerType==Speech.endpointerTypes.ENDPOINTER_EVENT_UNSPECIFIED){
      const transcription = data.results[0];
      console.log(`Transcription: ${transcription}`);
      fs.writeFile(fileName.replace(".","_")+".txt", transcription, (err) => {
        if (err) throw err;
        console.log('The file has been saved!');
      });
    }
  });
```

## Real request
If I execute this, the error is:

> Error: Audio data is being streamed too fast. Please stream audio data approximately at real time.

Did someone faced the same problem or have the correct hint to solve it?

#### Environment details

  - OS: Windows 10
  - Node.js version: 6.9.1
  - npm version: 3.10.8
  - google-cloud-node version: 150.0.0

Thanks!

**Comment by stephenplusplus** [comment]
I found an idea that might be helpful: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/364#issuecomment-232456193 -- please dig through these results as well to see if anything helps: https://www.google.com/search?q=Audio+data+is+being+streamed+too+fast.+Please+stream+audio+data+approximately+at+real+time

I'm going to close this issue here, because I don't believe this is an issue with our library. I think it has to do with the raw data of the request-- the incoming audio and the configuration-- both are things which we pass right through to the API.

Asking on StackOverflow using these tags might help as well: http://stackoverflow.com/questions/tagged/google-cloud-platform%20node.js%20google-cloud-speech. These tags have a tendency to attract help from more experienced users/developers of the API itself.

If you get absolutely nowhere, let me know and we can try to figure something out.
