### ISSUE TITLE
Vision 'detect' not returning values from remote url since 0.90.0

### ISSUE THREAD

**Issue by Jasonspd** [GoogleCloudPlatform/google-cloud-node#2215]
Follow this closed issue #2087 , I tried different versions of vision to see when it starts happening.

I was running vision 0.70.0 and install vision like this:
```
npm install google-cloud --save
var gcloud = require('google-cloud');
var vision = gcloud.vision();
```
And it detects remote URL's like a charm.

Since hearing this way of installing google-cloud is deprecated, I tried installing the bundle `@google-cloud/vision`. That's when I encountered the same error as the closed issue. Looking closely, the new install updated my version of vision. I tried 0.70.0 and 0.80.0 which works fine.

From 0.90.0 remote URL detects gives this error:
```
PartialFailureError: A failure occurred during this request.
    at /Users/jasonluu/Documents/v2/node_modules/@google-cloud/vision/src/index.js:420:15
    at /Users/jasonluu/Documents/v2/node_modules/@google-cloud/vision/src/index.js:121:5
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
```
errors: 
   [ { code: 500,
       message: 'image-annotator::error(12): We can not access the URL currently. Please download the image and pass it in.',
       type: 'labels' } ] }
```

**Comment by callmehiphop** [comment]
@stephenplusplus correct me if I'm wrong, but I'm guessing this popped up once we started passing the image uri to Vision instead of manually fetching it ourselves.

**Comment by stephenplusplus** [comment]
Yep, that's what's happened. We can't do anything about the API not being able to access the URL-- we can only return their error. To revert to our old behavior, aside from using the older module, you could do something like [what we used to](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/vision-0.8.0/packages/vision/src/index.js#L1376-L1387):

```js
var require('request')

request({
  method: 'GET',
  uri: image,
  encoding: 'base64'
}, function(err, resp, body) {
  // error handling omitted
  // `body` is a base64 representation of the image
  vision.detect(body, function(err) {})
})
```

If you think it's a bug with the Vision API, you can reach the API folks directly from the channels listed on their [support page](https://cloud.google.com/support).

**Comment by swayam18** [comment]
Opening this again because I don't think the workaround is a viable solution.
If you have hundreds of images to annotate in a short period of time the amount of memory you need to handle this case will sky rocket.

**Comment by ankit-joinwal** [comment]
We are facing this issue too- We are using below java libraries:
'com.google.apis:google-api-services-vision:v1-rev369-1.22.0',
 'com.google.apis:google-api-services-oauth2:v2-rev133-1.23.0',

Out of 50 requests (where we pass URL to Google Vision), 45 requests error out with below error:

**We can not access the URL currently. Please download the content and pass it in**

**Comment by stephenplusplus** [comment]
@ankit-joinwal I believe the correct repo to make an issue report for the Java library is here: https://github.com/GoogleCloudPlatform/google-cloud-java. This repo is for the Node.js client libraries.

@swayam18 In the earlier report, the official API (not our Node.js wrapper) was returning "We can not access the URL currently. Please download the image and pass it in." It would seem like the error is because their server cannot reach the URL you provided. That could be anything from a typo to a permissions issue. But, if you think the URL should be accessible from the Google server, do you have an example we can reproduce with?

**Comment by swayam18** [comment]
@stephenplusplus The same URL works at times, and doesn't work other times, so its difficult to come up with a reproducible url.

**Comment by stephenplusplus** [comment]
> The same URL works at times, and doesn't work other times

Do you mean from your end (the URL expires), or the Google end (the Vision API call fails)?

**Comment by swayam18** [comment]
Google end, its the same URL

**Comment by stephenplusplus** [comment]
Thanks. I think it would still help to have that URL, as maybe the Vision team could look through the logs to see if there's any more context available from its side.

@JustinBeckwith @swayam18 is providing a URL for analysis to Vision, and sometimes he gets an error from the API (not ours) that the URL cannot be accessed. Should we pass this report and the URL along to the Vision team for further review?

**Comment by ankit-joinwal** [comment]
@stephenplusplus 
Since the error is same at my end too. 
I can provide following sample images in case it helps us all.

https://media.cheggcdn.com/media%2Fcb6%2Fcb6cd4d5-9514-44b2-bc13-fbe2a7ba075b%2FphpfPVqJT.png
https://media.cheggcdn.com/media%2Fc0f%2Fc0f3d013-9c10-4a93-b04b-290a9b3e1b15%2FphpZrrY0q.png
https://media.cheggcdn.com/media%2F260%2F260698fa-d72c-40b0-b30c-860607d06d06%2FphpdTycEW.png

**Comment by swayam18** [comment]
@JustinBeckwith Did you manage to replicate the errors with Ankit's urls?
