### ISSUE TITLE
language module doesn't use default app credentials in GCF

### ISSUE THREAD

**Issue by bretmcg** [GoogleCloudPlatform/google-cloud-node#2364]
Using @google-cloud/language seems to require a keyfile, whereas the other ML APIs work without specifying when running in GCF/GAE.

The error I get is: "Google Cloud Natural Language API has not been used in project **p6072eb4b37b1c925-tp** before or it is disabled." -- no idea what this mysterious project is, and I can't access it in cloud console either.

#### Environment details

  - OS: Google Cloud Functions (Debian8/Jesse)
  - Node.js version: Google Cloud Functions (6.9.1)
  - npm version:
  - google-cloud-node version: 0.10.5 (also tried 0.10.3)

#### Steps to reproduce
```node
exports.myHttpFunction = function(req, res) {

  // Works with translate and vision: require('@google-cloud/xxx')(); 
  require('@google-cloud/language')().detectEntities('Axel Foley is from Detroit', 
      function (err, entities, apiResponse) {
        console.log('Default credentials');
        console.log(entities); //null
      }
    );
  
  require('@google-cloud/language')({
    projectId: 'fun-fun-functions',
    keyFilename: 'keyfile.json'
  }).detectEntities('Axel Foley is from Detroit', 
    function callback(err, entities, apiResponse) {
      console.log('Project ID and key file');
      console.log(entities); //populated
    }
  );
  
  require('@google-cloud/language')({
    projectId: 'fun-fun-functions'
  }).detectEntities('Axel Foley is from Detroit', 
    function callback(err, entities, apiResponse) {
      console.log('Only project ID specified');
      console.log(entities); //null
    }
  );
  
  require('@google-cloud/language')({
    keyFilename: 'keyfile.json'
  }).detectEntities('Axel Foley is from Detroit', 
    function callback(err, entities, apiResponse) {
      console.log('Keyfile only');
      console.log(entities); //populated
    }
  );

};
```

**Comment by stephenplusplus** [comment]
Thanks for reporting this. I just deployed the same script and it worked without a project ID or key file being specified. I'm not very well-experienced with Cloud Functions, but it seems like it put your script in the environment of a project with the name "p6072eb4b37b1c925-tp". And, whatever project that was, it did not have the Language API enabled, which is why the error was returned.

In other words, our code worked in that it detected the default environment and used the project ID and credentials associated with it. But, somehow, that project information did not match the project you were expecting. To dig in deeper as to how that happened, I believe you will need to contact the Cloud Functions team directly.
