### ISSUE TITLE
Add {debug,trace}-agent to the docs

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#2379]
We want to add [@google-cloud/debug-agent](https://npm.im/@google-cloud/debug-agent) and [@google-cloud/trace-agent](https://npm.im/@google-cloud/trace-agent) to the docs page. These provide background daemons that work with the Stackdriver Trace and Debug APIs. Other languages ([ruby example here]( https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-debugger/v0.25.0/google/cloud/debugger)) include the agents in their docs.

How do we go about adding these to the docs? The corresponding client libraries for Debug and Trace do not exist in this repo yet (and the agents do not publicly expose the client API). Do we create a placeholder for the non-existent client libraries to add the docs?

/cc @lukesneeringer @swcloud @JustinBeckwith

**Comment by stephenplusplus** [comment]
As it is now, we would need JSON files to live in this repo, so anytime the API changes upstream, we'd need a PR here with the updates (or some type of automation to push them here). We'd likely also need a placeholder directory, and some additions to various configuration files that are used by the docs site.

It looks like the JSDocs used over there should be pretty compatible with our system here. We have a rather complex documentation build (https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/scripts/docs), which might need to be modularized out so that other projects can use it.

cc @callmehiphop for any gotchas I might be overlooking.

**Comment by stephenplusplus** [comment]
@ofrobots is this still a goal? We've been relocating APIs and their docs off from GitHub and onto cloud.google.com.

**Comment by ofrobots** [comment]
@lukesneeringer @jmdobry How should we approach this in the post-mono-repo world?

**Comment by jmdobry** [comment]
I'll publish their API reference docs alongside the API reference docs of the other libraries.

**Comment by stephenplusplus** [comment]
@jmdobry do you have another place to track that, or do you want to keep this issue?

**Comment by jmdobry** [comment]
Tracking this elsewhere.
