### ISSUE TITLE
pubsub: topic.publish string payloads sent wrapped with quotation marks

### ISSUE THREAD

**Issue by fixermark** [GoogleCloudPlatform/google-cloud-node#2403]
#### Environment details

  - OS: (Google Cloud Function)
  - Node.js version: (Google Cloud Function default)
  - npm version:  (Google Cloud Function)
  - google-cloud-node version: ~0.10.0

#### Steps to reproduce

  1. const pubsub = require("`@google-cloud/pubsub`")();
  2. const topic = pubsub.topic('my-topic');
  3. topic..publish('hello!', (err) => console.log(err));

Expected result:
topic subscriber receives
hello!

Observed result
topic subscriber receives
"hello!"

(... i.e. it appears the data payload is escaped into a string before being sent instead of the string content itself being sent)

**Comment by fixermark** [comment]
As per the documentation, 

All messages not provided as `Buffer` will be published in JSON format.
If your receiving end uses another library, make sure it parses the
message properly.

... however, this is surprising in the raw string case, that the output is a JSON-ified string.

**Comment by stephenplusplus** [comment]
Yes, this was done so that the user would have a consistent way of handling the data. `JSON.parse()` (or its equivalent on the receiving end) should always work off the assumption google-cloud-node published something it can handle:

```
$ node -p "JSON.stringify('hi')"
"hi"
$ node -p "JSON.parse(JSON.stringify('hi'))"
hi
```

The Pub/Sub API is under a big re-factor that will force the users of google-cloud-node to only publish Buffer objects. This means you will be in charge of precisely what is sent to the Pub/Sub API. The next release of @&shy;google-cloud/pubsub will likely have this behavior. Stay tuned to the PR here: #2380.

Sorry for the confusion.
