### ISSUE TITLE
datastore.delete return same response when delete non-existent entity

### ISSUE THREAD

**Issue by jcsvwinston** [GoogleCloudPlatform/google-cloud-node#2424]
Try to delete one entity deleted recently, you will always get the same response from the API. err Object ramains null.

Thanks.

**Comment by jgeewax** [comment]
@jcsvwinston : What would you prefer? Are you hoping to delete and get some signal about whether the delete operation actually happened vs when it was a no-op? Can you share a bit more about your use case?

**Comment by jcsvwinston** [comment]
Sorry I think that I did't explain correctly. Let me show you with an example:

The result of a query get the next list of entities IDs:

- 5644406560391168
- 5664248772427776
- 5672749318012928
- 5682617542246400
- 5692462144159744
- 5720147234914304
- 5739407210446848

If I delete the entity with ID#5739407210446848, using this code:

```
datastore.delete(key, function(err,res) {
    console.log('Error:');
    console.log(err);
    console.log('========================================');
    console.log('API response:');
    console.log(res);
});
```

the response show:

> Error:
> null
> ========================================
> API response:
> { mutationResults:
>    [ { key: null,
>        version: '1499249992120000',
>        conflictDetected: false } ],
>   indexUpdates: 9 }

If I get the entities key list, you can check that previous entity ID doesn't exist:

- 5644406560391168
- 5664248772427776
- 5672749318012928
- 5682617542246400
- 5692462144159744
- 5720147234914304

If I try to remove again the same entity ID, I get the same previous response:
Error:
null
========================================
API response:
{ mutationResults:
   [ { key: null,
       version: '1499249992120000',
       conflictDetected: false } ],
  indexUpdates: 0 }


The question is that I never get and error when I try to remove an unexistent entity. The only one difference that I see is the value of indexUpdates, but it is not too clear for this operation.

Thanks

**Comment by jgeewax** [comment]
I think I follow what you're saying, but I'm trying to figure out what you would like to happen instead?

The idea here is when you call `datastore.delete(key)`, it returns a result (and potentially an error). If the error is blank, that key (at this point in time) no longer exists.

This could be because it never existed in the first place, or it could be because you deleted it, but it's gone now. What you're seeing is the equivalent of `DELETE FROM table WHERE id = 1234` in MySQL, which doesn't return an error if nothing matches, it just returns `Affected rows: 0`.

Are you saying you'd rather have an error thrown when you delete something and it is already gone?
 Maybe we could make that a flag `{errorOnMissing: true}`? That would ultimately just be shorthand for creating a transaction, getting the resource and depending on whether it exists or not, return the delete result or an error.

**Comment by lukesneeringer** [comment]
In SQL, if you issue a `DELETE` statement, you get back the number of rows that were deleted.

Say you have `my_table` with a bunch of rows (including one with an `id` of `42`). If you issue:

```sql
DELETE FROM my_table WHERE id = 42;
DELETE FROM my_table WHERE id = 42;
```

...the first statement will return `1`, and the second table will return `0`.

My inclination would be to do that, since it maps to the SQL standard.

**Comment by beaulac** [comment]
@jcsvwinston If you really want to throw an error if nothing was deleted, look at the `apiResponse.indexUpdates` property. 

Note that the second time you deleted that key, `indexUpdates` is `0`.

You could satisfy your requirement with a small wrapper function:
```javascript
function deleteOrThrow(keyOrKeys, cb) {
  datastore.delete(keyOrKeys, function (err, res) {
    if (!err && res.indexUpdates === 0) {
      err = new Error('Nothing was deleted!');
    }
    cb(err, res);
  });
}

// Optionally, you could even augment your datastore with it:
datastore.deleteOrThrow = deleteOrThrow;
```

**Comment by lantiaiot** [comment]
This solution solves my problem at the moment. I wasn't sure if IndexUpdates when 0 means that any entity was deleted.

But It would be more interesting as comment @lukesneeringer , if the method returns the number of deleted entities.

Thanks for your support.

**Comment by landrito** [comment]
Looks like this issue was resolved. I am closing.  Feel free to reopen. Thanks for filing this bug!
