### ISSUE TITLE
Running containers on GKE ignores serviceContext and shows "gke_instances"

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/google-cloud-node#2435]
#### Environment details

  - OS: Alpine 3.4
  - Node.js version: 7.10
  - npm version: N/A
  - google-cloud-node version: latest

#### Steps to reproduce

Running in a GKE Cluster with `GOOGLE_APPLICATION_CREDENTIALS` and `GCLOUD_PROJECT` correctly set (can access other APIs) with the following code:

```js
const cloudErrors = require('@google-cloud/error-reporting')({
  serviceContext: {
      service: 'APP_NAME',
      version: 'APP_REVISION'
    }
})

cloudErrors.report(new Error('Hello I am an Error')
```

will report errors coming from `gke_instances` ignoring the `serviceContext`

**Comment by kilianc** [comment]
@DominicKramer @ofrobots this is due to a race condition in the report client / our setup. The error was triggered before the keys and the context was setup (weird) and it was using default permission that comes with GKE.

I would expect this not to be the default behavior but at least now I know why it's happening.

Could this be happening while the node client is talking to the auth API ?

**Comment by DominicKramer** [comment]
Thank you for your feedback.  Yes, the expected behavior is that the service context provided to the error-reporting client will be the context used to report errors.

Were the errors first being reported under the `gke_instances` service and then, after some time, began being reported under the `APP_NAME` service?

**Comment by kilianc** [comment]
In our case we had `errorreporting.writer` missing from the service accounts roles so what I think was happening is:

* start server with correct ENVs
* start auth with `GOOGLE_APPLICATION_CREDENTIALS` and `GCLOUD_PROJECT`
* error in db connection
* report error with default auth (since GKE comes with `errorreporting.writer` by default)
* finish `GOOGLE_APPLICATION_CREDENTIALS` auth
* doesn't report anything anymore because of missing `errorreporting.writer`

Now that we fixed the problem I'll be curious to see if this happens again and is really a race condition, or an artifact of the role missing and the system falling back to "default" mode?

**Comment by DominicKramer** [comment]
Since you said that there was a db connection error, I have another possible explanation, and I wanted to get your input.  In particular, was the error in the db connection an `Error` that was thrown or an `Error` that was printed (along with its stack trace) to standard out or standard error?

That is, I created a GKE hello world app and made sure the cluster I created had the `https://www.googleapis.com/auth/cloud-platform` scope and that I enabled the `Stackdriver Error Reporting API` for the project.

The following code would then report an error to the error-reporting console using the custom service and version specified:
```javascript
var errors = require('@google-cloud/error-reporting')({
  serviceContext: {
    service: `Custom service`,
    version: `Custom version`
  }
});
errors.report(new Error('Some error'));
```

Howerver, with the following code, the error was reported to the error reporting console, but was reported under the `gke_instances` service.
```javascript
var errors = require('@google-cloud/error-reporting')({
  serviceContext: {
    service: `Custom service`,
    version: `Custom version`
  }
});
throw new Error('Some error');
```
This is because the error-reporting library does not, by default, handle `unhandledExceptions`.  As a result, the `Error` being thrown was handled and reported to the error reporting console by GKE functionality independent of the Node.js error reporting library.

Next, by adding an `uncaughtException` handler and reporting the error myself, the error was reported in the error reporting console under the custom service and version specified.
```javascript
var errors = require('@google-cloud/error-reporting')({
  serviceContext: {
    service: `Custom service`,
    version: `Custom version`
  }
});
process.on('uncaughtException', (e) => {
  errors.report(e);
  // Note: If you also uncomment the next line, the fact that an exception
  //       is printed to the application's output will be recognized by
  //       logic outside the error-reporting library, and the error will be
  //       reported to the error-reporting console.
  //
  //       In this case, since the error is reported by tools separate from
  //       the error-reporting library, the error will appear in the error
  //       reporting console under the `gke_instances` service.
  // console.error(e);
});

throw new Error('Some error');
```
Therefore, an `Error` being thrown could also be a possible explanation for the errors being displayed under the `gke_instances` service.

Further, if you forgot to enable the `Stackdriver Error Reporting API` for your project, you could still access other APIs, but the error-reporting library would not work.  In this case, you would see a message in the application's logs stating that the API needs to be enabled.

I just wanted to see whether or not this could explain what you observed.  If not, then I'll have to investigate more.  Thanks again for your feedback.

**Comment by kilianc** [comment]
I have this on my code:

```js
const onUncaughtException = (err) => {
  logger.error({
    env: process.env.NODE_ENV,
    revision: process.env.REVISION,
    service: process.env.APP_NAME,
    error: err.toString(),
    stack: err.stack && err.stack.split('\n')
  })

  cloudErrors.report(err)
  setTimeout(() => process.exit(1), 5000)
}

process
  .on('unhandledRejection', onUncaughtException)
  .on('uncaughtException', onUncaughtException)
```

What you said makes sense, I just checked and even the DB erroring on bootstrap are being reported correctly. So maybe default behavior kicked in.

**Comment by DominicKramer** [comment]
I just want to make sure I'm understanding correctly.  Did your original code not have an `uncaughtException` handler, but when you added one, the errors started being reported under the correct service. I want to make sure the problem was caused by thrown Errors being handled outside the error-reporting library. Thanks.

**Comment by vic3lord** [comment]
Having the same issue, also I cannot state `serviceContext` Object in logging-winston directly without using error-reporting.

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/logging-winston/src/index.js#L174

Let me know if I can do anything to help, even to provide info.

**Comment by landrito** [comment]
@kilianc any updates on this?

**Comment by ofrobots** [comment]
@vic3lord I have split your question into a separate issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2513 – I think it is a different issue.

**Comment by kilianc** [comment]
@DominicKramer not, I always had the handler setup and to this day I still see `gke_instances` every once in a while. Maybe it's a race condition win my code but on paper and looking at my code it seems technically impossible

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-error-reporting/issues/13.
