### ISSUE TITLE
Google common-grpc/speech crash on slow network connexion because of gRPC 

### ISSUE THREAD

**Issue by jaumard** [GoogleCloudPlatform/google-cloud-node#2443]
#### Environment details

  - OS: Max
  - Node.js version: 7
  - Yarn version: 0.24.6
  - google-cloud-node version:0.9.4

#### Steps to reproduce

  1. require `google-cloud/speech`
  2. just run google speech with a slow internet connexion 

This is related to https://github.com/grpc/grpc/issues/11514.

In my opinion it's urgent to fix as it make the all node project to crash when the error occurred.

**Comment by stephenplusplus** [comment]
Thank you for reporting! Because of our dependency on `grpc@^1.3.1` (https://github.com/GoogleCloudPlatform/google-cloud-node/blob/ac8967c92035f469c745995af61f261e9c37e427/packages/common-grpc/package.json#L46), new and re-installations of `@google-cloud/speech` will pick up `grpc@1.4.1` automatically.
