### ISSUE TITLE
Datastore apiResponse starcture

### ISSUE THREAD

**Issue by yonathan06** [GoogleCloudPlatform/google-cloud-node#2444]
Not a bug, just something missing from the docs (or very hard to find)
Where can I see the apiResponse starcture coming from the Datastore?
It doesn't appear in the API: [https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.0.3/datastore](https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.0.3/datastore )

Thanks

**Comment by lukesneeringer** [comment]
Hi @yonathan06,
Thanks for reporting this. We will see about getting this added.

**Comment by stephenplusplus** [comment]
We have recently pushed the raw API responses to the docs site: https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.0.3/datastore/v1/data_types

We don't link between the API method documentation and these full responses, so that's still a TODO, but I thought this might be helpful in the meantime.

**Comment by stephenplusplus** [comment]
We are in the process of splitting modules out from this monorepo into their own repos, e.g. https://github.com/googleapis/nodejs-storage. We are about half way through. As each API is split out, its docs migrate from our current GitHub-hosted site to cloud.google.com, e.g. https://cloud.google.com/nodejs/docs/reference/storage/1.4.x/

Given our progress in that direction, adding features to the GitHub-hosted docs isn't on the map.
