### ISSUE TITLE
bigquery table.exists is documented to return a boolean, but it returns an Array instead

### ISSUE THREAD

**Issue by xbill82** [GoogleCloudPlatform/google-cloud-node#2446]
#### Environment details

  - OS: Linux
  - Node.js version: v6.9.4
  - npm version: 5.1.0
  - google-cloud-node version: ^0.9.5

#### Steps to reproduce

  1. require `@google-cloud/bigquery`
  2. `bigQuery.dataset(this.dataSet).table(tableName).exists().then(exists => {return Array.isArray(exists})`
  3. check it returns `true`

But [the doc](https://googlecloudplatform.github.io/google-cloud-node/#/docs/bigquery/0.9.2/bigquery/table?method=exists) says the callback value is a `Boolean`.

**Comment by callmehiphop** [comment]
For the callback mode, the value is indeed a boolean, however for promisified versions we always return an array (since promises can only resolve with a single argument). Something we need to improve on is highlighting the promise docs, because as it is now we simple show its usage in the last example.

Sorry for any confusion this caused you!

**Comment by xbill82** [comment]
Oh, I understand. Is this documented somewhere?

**Comment by callmehiphop** [comment]
Well, if you go to the link you provided, the second example shows how to use that method with a promise. I don't think we explicitly state that promises return arrays anywhere.. but that is standard for every method in the library.

**Comment by stephenplusplus** [comment]
This is a similar issue as #2167-- we plan to add docs that explain the basics of how promises work across the library. Sorry for the confusion!
