### ISSUE TITLE
Error: Could not load the default credentials shows up randomly once a day

### ISSUE THREAD

**Issue by darciusal** [GoogleCloudPlatform/google-cloud-node#2501]
I have set up a google cloud function to monitor a bucket with frequent file changes.
The function reads files starting with a specific prefix and later generate new files to another bucket base on the files it reads, otherwise it will ignore the file and finish execution.
The function uses service account json to access/write files.
Those files starting with a specific prefix are updated only once a day.
The function is generating the new files properly and information seems correct.
However, by looking at the function logs, I notice that this error
 (Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information....) shows up once or twice a day. 
Could it be a bug in the gcloud library?

**Comment by darciusal** [comment]
I believe it's triggered by logging-winston which leads to the code here
https://github.com/google/google-auth-library-nodejs/blob/bd13376281a3af6e73fb729ea867950739c3c899/ts/lib/auth/googleauth.ts

**Comment by stephenplusplus** [comment]
@ofrobots any thoughts on this one?

**Comment by ofrobots** [comment]
Hi @darciusal! A few questions for you: What version of `google-cloud/logging-winston` are you using on your GCF application? Are there any other `google-cloud` libraries you are also using? Is there anything else functionally wrong in your function, or do you believe it is just the log messages that are being affected? The 'once or twice' errors you get, are they around a specific time, or at random times during the day.

I am trying to figure out if problem may be related to key expiry or whether it might be related to TCP timeouts in case your function got spun down to very low resources. Responses to the questions above might give me some clues.

**Comment by darciusal** [comment]
Hey @ofrobots,
I tried disabling logging-winston, but I was still getting this error.
I also encountered Auth error:Error: read ECONNRESET everyday.
For the function logic part, I have tried my best on making sure it's right. I have shared the function with you internally so you can confirm it as well.

Thanks!

**Comment by ofrobots** [comment]
Hi. I am pretty sure this issue is due to your Cloud Function getting throttled down to zero during periods of inactivity. Any TCP sockets that are pending at the time this happens will probably timeout/reset and error when the function is resumed on a subsequent request.

There are two different symptoms you reported here:
* `Error: Could not load the default credentials.`: This is reported by the `google-auth-library` (as you indicated above) which is used internally by both `storage` and `logging`. Subsequent requests to authenticate should succeed as the higher level libraries (e.g. logging) retry upon failure. Unless, of course, your function gets throttled again. I have opened https://github.com/google/google-auth-library-nodejs/issues/160 to get the `auth-library` to internally retry on socket timeout / connection reset.
* `Auth error:Error: read ECONNRESET`: This is coming from the gRPC library which is used by the logging library internally. It suggests the same throttling issue.

Fundamentally this means that, if your function is getting low enough traffic, the background work in your function may get starved due to throttling and as a result you may see those warnings.

One work-around you can try is by adding a delay before you terminate your function: 

```js
function eventHandler(event, callback) {
  // Your business logic here.
  // ...
  
  // delay terminating the function by a bit so that background tasks can drain.
 setTimeout(callback, 2000);
}
```

**Comment by darciusal** [comment]
Hi @ofrobots, Thanks for the response!
I have question on what do you mean for the "background work" you mentioned above.
Do you mean some of the business logic code that execute after the callback function is called?
If so, my function won't call the callback function until all logic are finish executing. (Example below)
```
const workPromise = createPromise();
workPromise.then(() => {...; callback()})
```
======
I have also noticed the ECONNRESET error before I used the winston function, so I am not sure if it is caused by the logging library.
======
Any chance do you think it is similar issue to this?
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2254
I thought they already changed the default forever agent to false though.

**Comment by gaofanmichael** [comment]
This issue was moved to googleapis/nodejs-logging-winston#1

**Comment by dizid** [comment]
I have:
Error: Could not load the default credentials.
But ONLY in Visual Studio Code.
In the terminal the same node googletest.js works perfectly.
I used the "export GOOGLE_APPLICATION_CREDENTIALS="path-to.json" command.
Because the exact same code works in the terminal (and shows me a list of buckets) but not in VS Code, i think this is a bug in VS Code.
![2018-02-01-130629_1600x900_scrot](https://user-images.githubusercontent.com/314100/35679225-89800c16-0756-11e8-9a5f-952876db7f1b.png)
