### ISSUE TITLE
URLs in the API reference doc is not working. 

### ISSUE THREAD

**Issue by vr001** [GoogleCloudPlatform/google-cloud-node#2546]
https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/not-found
When clicking the annotateImageResponse, the URLs are not working.

**Comment by vr001** [comment]
Every URL, linked on this page is broken. 

https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.12.0/vision/v1/data_types

The below one is the broken URL. 
https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.12.0/vision/v1/data_types?method=BatchAnnotateImagesResponse

**Comment by vr001** [comment]
Is there any updates on this?

Without references not sure how I can use api's or am i missing something obvious? Thanks.

**Comment by stephenplusplus** [comment]
Where you encounter a broken URL, instead of clicking on the link, just search the page for it. For example, for [this method](https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.12.0/vision/v1/data_types?method=AnnotateImageResponse), it shows a link for `FaceAnnotation`. Instead of clicking that link, you can either search or go to the top of the page to find the correct section of the page.

Every type is on the same page, so it's just a matter of finding it. I'm sorry for the inconvenience. I would like to look at this again next week to correct the links.

**Comment by vr001** [comment]
@stephenplusplus Simple. Can you point where is the response for the _faceAnnotation_ 
Right now, i am using the reference from the [REST API](https://vision.googleapis.com/$discovery/rest?version=v1) page. Thanks.

**Comment by stephenplusplus** [comment]
https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.12.0/vision/v1/data_types?method=FaceAnnotation

**Comment by stephenplusplus** [comment]
I think this will be a "won't fix", unfortunately, as we are almost complete in moving our documentation off of gh-pages and onto cloud.google.com.

Sorry for the inconvenience. The information is there, you just have to search the page with "Ctrl+F" instead of the broken link. (See my previous post)
