### ISSUE TITLE
How to get the actual value of a callback when topic.publish'ing?

### ISSUE THREAD

**Issue by gunar** [GoogleCloudPlatform/google-cloud-node#2551]
How to get the actual value of a callback when topic.publish'ing?
The following gets me the messageId only.

Publishing
```js
  topic.publish('New message!', function(err, messageIds, apiResponse) {
    // messageIds, but no value from the callback
  });
```
Elsewhere
```js
exports.event = (event, callback) => {
  callback(null, 'some value')
}
```

Thanks in advance!

**Comment by stephenplusplus** [comment]
Do you mean you want the value of the message that you just published? The upstream API does not return this as part of the response, which is why we haven't either. The Pub/Sub API is going through a large rewrite (#2380) and is expected to release within the next day or so. As part of the migration, all messages will have to be published as a raw Buffer object. This means there will no longer be ambiguity in how your message is passed to Pub/Sub and saved, which should also address this issue-- you can assume the value is the same as what you just passed to `publish`.

In the current release of Pub/Sub (`<=0.13.2`), the value that is published is:

```js
new Buffer(JSON.stringify('New message!')).toString('base64')
```

To prepare for the new release, feel free to check out the docs here: https://stephenplusplus.github.io/gcloud-node/#/docs/pubsub/master/pubsub.

Hope this helps!

**Comment by gunar** [comment]
@stephenplusplus Thank you. So it seems my question is about PubSub API, not `google-cloud-node`. I'll ask anyway, in hopes that you are able and willing to answer it.

How can I get the value of the message that I just published?

Thanks in advance.

**Comment by stephenplusplus** [comment]
I'm sorry, I'm not sure of a great answer for that. You can try contacting the Pub/Sub team / fellow users using the methods mentioned on the [Support page](https://cloud.google.com/pubsub/docs/support).

**Comment by gunar** [comment]
@stephenplusplus Got it. Thank you. Well, can you at least tell me where this message goes to? Is it stored/published in the same topic, or does it go nowhere? Thank you again.
