### ISSUE TITLE
feat: support for Google Container Engine

### ISSUE THREAD

**Issue by bcoe** [GoogleCloudPlatform/google-cloud-node#2578]
## Feature Request/Question

Hello 👋 

I've been working on automating the deployment of kubernetes clusters at npm, Inc. When searching on npm for existing API clients, I found the great ecosystem of `@google-cloud` modules published to npm (It's cool to see scopes being used effectively in open-source).

Unfortunately, I didn't find a module published for Google Container Engine; Because of the nice modular way you've built your API, I was able to pull something together pretty quickly:

https://github.com/bcoe/google-container-engine

I was curious if this was something you would eventually plan on adding to the `google-cloud-node` (if so, I'd happily pitch in since I'd love to have the abstraction). I eventually did realize that this API is supported in https://github.com/google/google-api-nodejs-client; what drives the decision behind what APIs are pulled into google-cloud-node vs. google-api-nodejs-client; it definitely tripped me up a bit that both projects exist.

**Comment by stephenplusplus** [comment]
👋 Thank you for this!

"google-api-nodejs-client vs google-cloud-node" was originally "auto-generated API clients vs idiomatic, handwritten API clients". We try to make things easier from the authentication process through making the request in a way that wasn't robotic. It's been a few years since we've started, and we're now landing somewhere in the middle; we've made a *new* generated layer that's easier to use, so we're working towards making the handwritten layer thinner.

It looks like it's possible to have a client generated for Container Engine (they start as [proto files](https://github.com/googleapis/googleapis/blob/master/google/container/v1/cluster_service.proto)). I'm going to pass this along to @lukesneeringer to prioritize and advise on how we should proceed.

**Comment by lukesneeringer** [comment]
> what drives the decision behind what APIs are pulled into google-cloud-node vs. google-api-nodejs-client; it definitely tripped me up a bit that both projects exist.

This is a common problem. The decision behind what APIs belong where is "how fast can we move things from the old way to the new way?" :-)

I actually do not know how easy Container Engine gen would be -- it needs to be on a particular architecture within Google, for example. If it really is just a library gen, then I would not object to tossing it here if I have all the artifacts I need, and would be happy to accept an abstration layer on top of it (but I would want it to conform to a specific design -- we could talk about that if the previous predicates all return true).

**Comment by lukesneeringer** [comment]
@ethanbao Any idea whether a GAPIC for Container Engine is possible?

**Comment by bcoe** [comment]
@lukesneeringer @stephenplusplus thanks for the clarification, excited to see where you land -- am definitely unblocked for the time being.

**Comment by stephenplusplus** [comment]
I've moved this as a request bullet in our "API Implementation Tracker": #1338.
