### ISSUE TITLE
getFiles does not return ApiResponse if autoPaginate is true (the default)

### ISSUE THREAD

**Issue by esprehn** [GoogleCloudPlatform/google-cloud-node#2594]
#### Environment details

  - OS: OS X
  - Node.js version: v6.10.3
  - npm version: 3.10.10
  - google-cloud-node version: 1.2.1

#### Steps to reproduce

  1. require `google-cloud`

```js
bucket.getFiles({ delimiter: '/' }, function(err, files, nextQuery, api) {
  console.log(err, files, nextQuery, api);
});
```

Will print `null [] undefined undefined`.

This is very confusing, it seems you need to pass autoPaginate: false to get the api response back.

Looking at the code I don't know where this happens, the code does:

```js
    var nextQuery = null;
    if (resp.nextPageToken) {
      nextQuery = extend({}, query, {
        pageToken: resp.nextPageToken
      });
    }

    callback(null, files, nextQuery, resp);
```

And if you console.log(resp) here it's non-undefined,  but by the time it gets to your callback it's undefined. Where did the extra arguments end up?

Note also that while other apis return the ApiResponse in the second position of the array, getFiles does't so you can't do:

```js
const [files, api] = await bucket.getFiles({ delimiter: '/' });
console.log(api.prefixes);
```

and instead you must pass a callback.

**Comment by esprehn** [comment]
Looks like this is paginator.run_:

```js
  if (autoPaginate) {
    this.runAsStream_(parsedArguments, originalMethod)
      .on('error', callback)
      .pipe(concat(function(results) {
        callback(null, results);
      }));
```

It's super confusing and not at all clear that to list the sub-directories you need to do getFiles with delimiter: '/', paginate turned off, and pass a callback. It'd be really nice this API could be made more ergonomic. :)

**Comment by stephenplusplus** [comment]
The apiResponse pattern is library-wide and could certainly be re-opened for discussion. Many of our API calls are not autopagination methods, and because of this, it's easy to return our simplified response alongside the raw API response. However, the autopagination methods involve multiple raw API responses, which is why we didn't include them; it wouldn't be clear which of many objects were relevant to the user.

Do you think we should return an array of responses?

A couple notes;

For list operations, we assign the relevant section of the raw API response to our custom object that's returned. E.g., for storage.getFiles, each returned File object has a metadata property that includes many details from the API response. I'm pointing this out just to note that we don't discard the entire API response, just the outer shell.

The other way to fix this problem (and ones like it) is to add a new method to get what you're after, e.g. storage.getDirectories()

@callmehiphop @lukesneeringer for thoughts.

**Comment by esprehn** [comment]
There's two problems here, the first is that the docs are confusing and show examples with apiResponse but never explain that you need to pass autoPaginate: false:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/1.2.0/storage/bucket?method=getFiles

The second is that getting the list of sub-directories is hard and has some confusing surprises. Google Storage has files, prefixes and sometimes prefixes are also files...

ex. I'm seeing:

`getFiles({ prefix: 'foo', delimiter: '/', autoPaginate: false })` returns the prefixes 'foo/' and no files.

`getFiles({ prefix: 'foo/', delimiter: '/', autoPaginate: false })` returns prefixes 'foo/bar' and 'foo/baz' and a single file with the name 'foo/'.

I assume this is because creating a folder in the console generates a _$folder$ file, while just uploading a file with a prefix doesn't, and getFiles() will return the magic $folder$ files (though the name is just foo/ without the $ stuff), but not the ones that are just prefixes?

**Comment by stephenplusplus** [comment]
@frankyn might be able to help with those questions about the Storage API.

**Comment by esprehn** [comment]
The docs seem to contradict the results here, I mostly want the GoogleStorage node API to behave similarly to what gsutil does. :)

ex. creating a folder in the console does not create a file with _$folder$ anymore, I just get a file with a / on the end and application/x-www-form-urlencoded;charset=UTF-8 as the Content-Type.

I'm happy to migrate that part of this discussion elsewhere if you tell me where to file those bugs.

Separately a new getDirectories() API would be super useful. Lots of folks all over are trying to figure out how to make the Google Storage API behave like gsutil, and needing to remember to pass delimiter: '/', prefix, autoPaginate, and then potentially filter out yourself (since the prefix can *both* be a prefix and a file of the same name, but not always) is a lot of ceremony to list some files.

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-storage#26
