### ISSUE TITLE
Node Cloud Examples and API have different functions

### ISSUE THREAD

**Issue by thebluejay** [GoogleCloudPlatform/google-cloud-node#2620]
I'm writing a Google Cloud Function that runs Cloud Vision text detection on images, and I have working text detection using the same example seen here: https://cloud.google.com/vision/docs/detecting-text, which says to use the `textDetection` function like so:

```
const Vision = require('@google-cloud/vision');

// Instantiates a client
const vision = Vision();

// Performs text detection on the local file
vision.textDetection({ source: { filename: fileName } })
...
```
This is in contrast to the Cloud API for node (https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.11.4/vision) that documents a `detectText` function but not `textDetection`. Moreover, the `detectText` function will return an error if you try to use it like specified in the API:

`TypeError: vision.detectText is not a function`

Are these two resources differing simply because the API hasn't been updated yet?

**Comment by stephenplusplus** [comment]
Sorry for the confusion-- starting at 0.12.0, `@google-cloud/vision` follows the API from the cloud.google.com docs. Our API docs defaulted to an older version due to a metadata file we forgot to update. That's been done, and the docs are now accurate: https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision

Thanks for the heads up!

**Comment by thebluejay** [comment]
Glad it's fixed :+1:

**Comment by TheOska** [comment]
I got the same problem with other function that returns the error 
TypeError: vision.documentTextDetection is not a function
But detectText is worked.
