### ISSUE TITLE
Vision WEB_DETECTION response doesn't include visuallySimilarImages

### ISSUE THREAD

**Issue by sararob** [GoogleCloudPlatform/google-cloud-node#2693]
The `webDetection` response JSON (docs [here](https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#WebDetection)) includes `visuallySimilarImages` - it looks like the Node client is missing this part of the response (looking [here](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/vision/src/v1/doc/doc_web_detection.js)).

**Comment by lukesneeringer** [comment]
Hi @sararob,
We should just sent back whatever response we get from the API (although our documentation may be out of date).

Are you not actually getting that key? If so, could you show me what code you are running?

Thank you so much. :-)

**Comment by stephenplusplus** [comment]
It looks like there is a pre-release version of Vision, `v1p1beta1`, that has that property in it: https://github.com/googleapis/googleapis/blob/9b2f51ba794fd23a1fa738239695ddbbee42888f/google/cloud/vision/v1p1beta1/web_detection.proto#L100.

Our API uses v1, which is why we don't have it: https://github.com/googleapis/googleapis/blob/9b2f51ba794fd23a1fa738239695ddbbee42888f/google/cloud/vision/v1/web_detection.proto#L64-L77

When we upgrade the API here (presumably after it's officially launched) it will be supported automatically.
