### ISSUE TITLE
Access underlying HTTP response status codes

### ISSUE THREAD

**Issue by ccnixon** [GoogleCloudPlatform/google-cloud-node#2761]
#### Environment details

  - OS: MacOS
  - Node.js version: 8.4.0
  - npm version: 5.3.0
  - @google-cloud/pubsub version: 0.15.0

#### Steps to reproduce

  1. require `@google-cloud/pubsub`
  2. Publish a message to a topic that triggers an error (unauthenticated for example)
  3. Struggle to translate the grpc error message / code into a standard HTTP status code

When using the node client library, the error responses returned to the client are grpc errors (bad creds for example returns a code of 16 and a message of `invalid_client`).

I'm curious if there's a way to access the actual http response from the API using the client? Ideally it would be great to be able to get responses that conform to this protocol:

https://cloud.google.com/pubsub/docs/reference/error-codes

Alternatively, is there someplace where all the potential grpc errors are documented so I could create my own mapping?

Thanks!

**Comment by callmehiphop** [comment]
@ccnixon As far as I know it is not possible to get HTTP codes from gRPC responses. We put together [a map](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/common-grpc/src/service.js#L44) (which is going away pretty soon) if you'd like to compare.

Otherwise I often find myself referencing the [go docs](https://godoc.org/google.golang.org/grpc/codes). Hopefully this helps!

**Comment by ccnixon** [comment]
@callmehiphop - thanks, the map looks great assuming for the time being.

**Comment by ccnixon** [comment]
@callmehiphop - do you know when that mapping is expected to go away and what will be replacing it? It looks like it's different from the Go status definitions.
