### ISSUE TITLE
Is it worth adding an adaptor to make SocketCluster client work with PubSub?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#703]
Docs: http://socketcluster.io/#!/docs/middleware-and-authorization

**Comment by stephenplusplus** [comment]
Definitely :+1: I'll try to play with this soon, probably after getting us on v1 of PubSub (#699).

**Comment by stephenplusplus** [comment]
@callmehiphop did some playing around with this and got further than I did. Do you have any examples of what the integration looks like or questions, issues, etc?

**Comment by callmehiphop** [comment]
I haven't played with it for *too* long, but integration doesn't look to be very difficult. Socketcluster emits events allowing you subscribe, unsubscribe and publish respectively.

My questions mostly revolve around PubSub because of my lack of familiarity with it -- I'm not sure if I should be creating topics/subscriptions or if those should have been created previously via dev console, etc. 

[Here](https://github.com/callmehiphop/pubsub-sc-playground/blob/master/lib/sc-gcloud.js) is a (bad) example of how you would integrate a backend service with Socketcluster.

**Comment by stephenplusplus** [comment]
@tmatsuo - can you help explain the basics of integrating with this library? (See @callmehiphop's questions above)

**Comment by stephenplusplus** [comment]
Ping @tmatsuo. Is this an integration worth making?

**Comment by tmatsuo** [comment]
Sorry I missed the comment above somehow. Honestly I'm not sure about your question without knowing sockercluster more.

**Comment by stephenplusplus** [comment]
@lukesneeringer This issue dates back a couple of years, when we were trying to find ways to show integrations with what we were building and other libraries that already existed in the same space. Things have changed since then, with cloud.google.com now showing integrations via tutorials and QuickStarts.

Should we look at this request in a modern light and consider including integrations as part of [in-repo samples](https://github.com/googleapis/nodejs-storage/tree/master/samples)? Leave it to the docs writers to mention in cloud.google.com documentation? Drop the idea of integrations altogether?

**Comment by stephenplusplus** [comment]
Please re-open if there's more to do here.
