### ISSUE TITLE
Implement spy library for cleaner spec files

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#871]
There's a bit of clutter in our test files when stubbing out methods in our unit tests - https://github.com/GoogleCloudPlatform/gcloud-node/blob/469c3ac4a81dcd43dfd1d1b8bbc84cea6afe49dd/test/bigquery/table.js#L38.

I propose we implement a spy library to clean up some of this.

**Comment by stephenplusplus** [comment]
:+1:

**Comment by callmehiphop** [comment]
I've really only used jasmine and sinon for spies, jasmine obviously doesn't fit.. so sinon? Not particular partial to it though.

**Comment by stephenplusplus** [comment]
Sorry to assign/re-assign! I think it might be best if you take first crack at this. Maybe just do a test file so I can see the patterns you use, then I can do the grunt work of applying it suite-wide.

**Comment by callmehiphop** [comment]
No worries! This is what I was kind of thinking

```javascript
var sinon = require('sinon').sandbox.create();

describe('SomeObject', function() {

  afterEach(function() {
    sinon.restore();
  });

  describe('method', function() {
    it('should do something', function() {
      var data = {};

      sinon.stub(util, 'someOtherMethod', function() {
        return data;
      });

      assert.strictEqual(SomeObject.method(), data);
    });
  });
});
```

If this isn't enough to go on, I'll try and get a real example going soon!

**Comment by stephenplusplus** [comment]
I tried re-writing a few things with sinon, but ended up with code that looked very similar, except using an abstraction rather than "just plain JavaScript" of overwriting a method. That doesn't mean this is a bad idea at all, but probably just that I'm not seeing what you see see.

Could you show how you would re-write the example from your first post? (https://github.com/GoogleCloudPlatform/gcloud-node/blob/469c3ac4a81dcd43dfd1d1b8bbc84cea6afe49dd/test/bigquery/table.js#L38)

**Comment by stephenplusplus** [comment]
Going to close since @callmehiphop has started integrating sinon where it was helpful for Bigtable. I don't think the cost of a full re-write of our tests is worth it, but we can continue injecting it where we see its value. If you feel differently, just re-open!
